lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem' # Changez le chemin si nécessaire
    public_key: '%kernel.project_dir%/config/jwt/public.pem'   # Changez le chemin si nécessaire
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600
