nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:5173']
        allow_credentials: true
        allow_headers: ['content-type', 'authorization', 'x-custom-header']
        expose_headers: ['Link', 'X-Total-Count']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['http://localhost:5173']
            allow_headers: ['content-type', 'authorization', 'x-custom-header']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            max_age: 3600